package te.interview.prep.strings_arrays

import spock.lang.Specification
import spock.lang.Subject

class SentenceSimilarityDeterminerTest extends Specification {

    @Subject
    SentenceSimilarityDeterminer sentenceSimilarityDeterminer = []

    def "can determine if two sentences are similar"() {
        expect:
            sentenceSimilarityDeterminer.determine(sentence1.split(), sentence2.split(), pairs) == isSimilar

        where:
            sentence1               | sentence2              | pairs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    || isSimilar
            "great"                 | "great"                | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       || true
            "great dude"            | "great"                | [["great", "dude"]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      || false
            "great acting skills"   | "fine drama talent"    | [["great", "fine"], ["acting", "drama"], ["skills", "talent"]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           || true
            "great acting skills"   | "fine painting talent" | [["great", "fine"], ["drama", "acting"], ["skills", "talent"]]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           || false
            "an extraordinary meal" | "one good dinner"      | [["great", "good"], ["extraordinary", "good"], ["well", "good"], ["wonderful", "good"], ["excellent", "good"], ["fine", "good"], ["nice", "good"], ["any", "one"], ["some", "one"], ["unique", "one"], ["the", "one"], ["an", "one"], ["single", "one"], ["a", "one"], ["truck", "car"], ["wagon", "car"], ["automobile", "car"], ["auto", "car"], ["vehicle", "car"], ["entertain", "have"], ["drink", "have"], ["eat", "have"], ["take", "have"], ["fruits", "meal"], ["brunch", "meal"], ["breakfast", "meal"], ["food", "meal"], ["dinner", "meal"], ["super", "meal"], ["lunch", "meal"], ["possess", "own"], ["keep", "own"], ["have", "own"], ["extremely", "very"], ["actually", "very"], ["really", "very"], ["super", "very"]] || true
            "one excellent meal"    | "one good dinner"      | [["great", "good"], ["extraordinary", "good"], ["well", "good"], ["wonderful", "good"], ["excellent", "good"], ["fine", "good"], ["nice", "good"], ["any", "one"], ["some", "one"], ["unique", "one"], ["the", "one"], ["an", "one"], ["single", "one"], ["a", "one"], ["truck", "car"], ["wagon", "car"], ["automobile", "car"], ["auto", "car"], ["vehicle", "car"], ["entertain", "have"], ["drink", "have"], ["eat", "have"], ["take", "have"], ["fruits", "meal"], ["brunch", "meal"], ["breakfast", "meal"], ["food", "meal"], ["dinner", "meal"], ["super", "meal"], ["lunch", "meal"], ["possess", "own"], ["keep", "own"], ["have", "own"], ["extremely", "very"], ["actually", "very"], ["really", "very"], ["super", "very"]] || true
    }

}
